#ifndef enum_h__
#define enum_h__


enum SCENEID { SC_LOGO, SC_TUTORIAL_THREAD, SC_TUTORIAL, SC_STAGE, SC_STAGE2, SC_STAGE3, SC_END };
enum LAYERID { LAYER_ENVIRONMENT, LAYER_GAMEOBJECT, LAYER_UI, LAYER_END };
enum COLORPARTID { PART_RUU, PART_RUD, PART_RDU, PART_RDD, PART_LUU, PART_LUD, PART_LDU, PART_LDD, PART_END };

enum PLAYERSTATE
{
	STATE_IDLE1,	//0
	STATE_IDLE2,	//1
	STATE_WALK,		//2
	STATE_RUN,		//3
	STATE_JUMP,		//4
	STATE_FALL,		//5
	STATE_PULL,		//6
	STATE_PUSH,		//7
	STATE_HANG,		//8
	STATE_SHOOT,	//9
	STATE_SLIDE,	//10
	STATE_DIE,		//11
	STATE_END		//12
};

enum SKULLSTATE { SKULL_IDLE, SKULL_READY, SKULL_FALL, SKULL_CRASH, SKULL_UP, SKULLSTATE_END };
enum ROCKSTATE { ROCK_IDLE, ROCK_FALL, ROCK_IMPACT, ROCK_FLYING, ROCK_END };

enum CUBEID
{
	CUBE_DECO,
	CUBE_BRICK,
	CUBE_CRATE,
	CUBE_PLATFORM,
	CUBE_SKULL,
	CUBE_ROPE,
	CUBE_LASER,
	CUBE_SPIKES,
	CUBE_STAIRS,
	CUBE_ROCK,
	CUBE_BALLOON,
	CUBE_END
};

enum OBJID
{
	OBJ_DECO, OBJ_KEY, OBJ_DOOR, OBJ_DOORLOCK, OBJ_BATTERY, OBJ_SAVEPOINT, OBJ_END
};

enum CAMERA_ZOOM_TYPE { ZOOM_VERY_NEAR, ZOOM_NEAR, ZOOM_DEFAULT, ZOOM_FAR, ZOOM_VERY_FAR, ZOOM_TYPE_END };

enum SKULLDUSTEFFECTID { SKULLDUST_ONE, SKULLDUST_TWO, SKULLDUST_THREE, SKULLDUST_FOUR, SKULLDUST_FIVE, SKULLDUST_SIX, SKULLDUSTID_END };

enum FIRESPAWNPOS { LEFT_DOWN, LEFT_UP, RIGHT_DOWN, RIGHT_UP, FIRESPAWN_END };

enum CAMERAOBSERVER_DATA
{
	DATA_NARRATIVE_MOVEING = 4, DATA_NARRATIVE_VIEW, DATA_PLAYER, DATA_STATICCAMERA, DATA_COLORCIRCLEACTIVE,
	DATA_DOOR, DATA_SCENEID, DATA_COLORCIRCLE, DATA_KEY, DATA_OUTLINE, DATA_PLAYERTUTO, DATA_PLAYERTUTOPOS, DATA_TUTOCAMERA, DATA_LISTTUTOTOBJECT
};

enum NARRATIVE_VIEW
{
	DEFAULT,FIRST_PERSON
};

enum DUSTEFFECTID { DUST_ONE, DUST_TWO, DUST_THREE, DUST_FOUR, DUST_FIVE, DUST_SIX, DUSTID_END };

enum CLOUDID { CLOUD_FIRST, CLOUD_SECOND, CLOUD_THIRD, CLOUD_END };

enum OBJECTNAME { SKYBOX, CLOUD, BUTTON_X, OBJECTID_END };

enum BALLOON_COLCHECK
{
	COL_BALLOON, COL_BALLOONCUBE, COL_END
};

namespace CHECK
{
	enum SIDE { SIDE_UP, SIDE_DOWN, SIDE_LEFT, SIDE_RIGHT, SIDE_END };
}

enum BALLOON_STATE
{
	BALLOON_UP, BALLOON_DOWN, BALLOON_STOP, BALLOONSTATE_END
};

enum CUBE_BULLETID
{
	BULLET_NORMAL, BULLET_STOP, BULLETID_END
};
#endif // enum_h__
